#!/bin/bash
#
# bootstrap installs things.

function installTools() {
	sudo -v #ask password beforehand
	source ~/dotfiles/installscript
}


echo 'Install tools'
echo '------------------'
echo 'Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
   installTools
fi
